export const routes = {
  home: "/",
  products: "/products",
  blog: "/blog",
  services: "/services",
  work: "/work",
  roadmap: "/roadmap",
  contact: "/contact",
  product: (slug: string) => `/products/${slug}`,
  productDownload: (slug: string) => `/products/${slug}/download`,
  productGuide: (slug: string) => `/products/${slug}/guide`,
  productPrivacy: (slug: string) => `/products/${slug}/privacy`,
  productReleases: (slug: string) => `/products/${slug}/releases`,
  blogPost: (slug: string) => `/blog/${slug}`,
  service: (slug: string) => `/services/${slug}`,
};
