export const routes = {
  home: "/",
  products: "/products",
  lab: "/lab",
  tools: "/tools",
  blog: "/blog",
  services: "/services",
  work: "/work",
  roadmap: "/roadmap",
  contact: "/contact",
  about: "/about",
  adminLogin: "/admin/login",
  admin: "/admin",
  privacy: "/privacy",
  terms: "/terms",
  product: (slug: string) => `/products/${slug}`,
  productDownload: (slug: string) => `/products/${slug}/download`,
  productGuide: (slug: string) => `/products/${slug}/guide`,
  productPrivacy: (slug: string) => `/products/${slug}/privacy`,
  productReleases: (slug: string) => `/products/${slug}/releases`,
  tool: (slug: string) => `/tools/${slug}`,
  blogPost: (slug: string) => `/blog/${slug}`,
  blogCategory: (slug: string) => `/blog/category/${slug}`,
  blogTag: (slug: string) => `/blog/tag/${slug}`,
  blogSearch: "/blog/search",
  service: (slug: string) => `/services/${slug}`,
};
